### PR TITLE
changed follow links logic

### PR DESCRIPTION
**Pull request by gitmathub**
Hi Andreas,

Thank you for this great plugin. Sadly it failed for me, because my provider does not allow symlinks. This means neither `+FollowSymlinks` nor `+SymLinksIfOwnerMatch` is allowed. Which is not much of a surprise as the apache .htaccess comments state it:
```
#   If your web host doesn't allow the `FollowSymlinks` option,
#   you need to comment it out or remove it, and then uncomment
#   the `Options +SymLinksIfOwnerMatch` line (4)
```

This combination doesn't work with the current version of the plugin. So I have extended it a bit. The following logic applies:

a.) no configuration -> +FollowSymlinks, NO +SymLinksIfOwnerMatch
b.) DisallowSymLinks: TRUE -> NO +FollowSymlinks, NO +SymLinksIfOwnerMatch
c.) SymLinksIfOwnerMatch: TRUE -> +FollowSymlinks, +SymLinksIfOwnerMatch

Please review my changes. If you like them then merge them into the code.

If you have any questions or disagree. Just drop me a line.

Cheers,
Mat

### CODE REVIEW

**Comment by AndreasFaust** [comment]
Thank you, Mat, for this well implemented PR. Everything works like expected. 
There is only one question: `SymLinksIfOwnerMatch: true` inserts both commands. 
I thought, it’s either `+FollowSymlinks` OR `+SymLinksIfOwnerMatch`. Is there a particular reason, why you want them both? And does it work that way? (You see: I am not an Apache-expert. I just wrote this plugin to get this `htaccess`-thing out of my way.)

**Comment by gitmathub** [comment]
> There is only one question: SymLinksIfOwnerMatch: true inserts both commands.

My reasoning ist the following:
- `FollowSymlinks` is enabled by default. And `SymLinksIfOwnerMatch` by default disabled.
- if you enable `SymLinksIfOwnerMatch` then both are enabled.

Does this make sense?

**Comment by AndreasFaust** [comment]
I understand. My question was: Do both commands work together? Or must `+FollowSymlinks` be deleted from the `.htaccess`-file when `+ SymLinksIfOwnerMatch` is inserted?

**Comment by gitmathub** [comment]
Ah, now I get your point. I'm not an apache expert. But I'm trying to find an answer to that and coming back to you.

**Comment by gitmathub** [comment]
O dear, there are so many opinions out there, all not helping. But luckily the apache documentation answered the question :-)

**Question**: Can *FollowSymlinks* and *SymLinksIfOwnerMatch* be used at the same time?

**Answer**: yes

## Version

I refer to the current Apache version: 2.4 [apache docs](http://httpd.apache.org/docs/). The functionality seems to be the same as older versions. A change is, that the newer version has only *FollowSymLinks* enabled as a default.
(@AndreasFaust you are mentioning version 3 in the README? I believe 2.4 is the right version)

## Configuration Options

1) Apache default [reference:apache 2.4 doc](https://httpd.apache.org/docs/current/mod/core.html#options)
 
```
Options +FollowSymlinks
# Options +SymLinksIfOwnerMatch
```

2) Some provider don't allow *FollowSymLinks*. H5BP suggests to comment *FollowSymLinks* out and to uncomment *SymLinksIfOwnerMatch* [reference: h5bp git repository: rewrite engine](https://github.com/h5bp/server-configs-apache/blob/master/src/rewrites/rewrite_engine.conf)

```
# Options +FollowSymlinks
Options +SymLinksIfOwnerMatch
```

1) What happens if both options are enabled? The Apache doc says in the [SymLinksIfOwnerMatch section](http://httpd.apache.org/docs/2.4/mod/core.html#options) that the most specific option will be valid: 

> Normally, if multiple Options could apply to a directory, then the most specific one is used and others are ignored; the options are not merged

As the SymLinksIfOwnerMatch is the same functionality but more restrictive as FollowSymLinks it is more *specific*.

This configuration is valid and the *SymLinksIfOwnerMatch* will apply:
```
Options +FollowSymlinks
Options +SymLinksIfOwnerMatch
```

**Comment by AndreasFaust** [comment]
Thank you, @gitmathub!

**Comment by gitmathub** [comment]
Thank you and happy new year!

**Pull request merged**
